spring:
  datasource:
    url: jdbc:postgresql://$containers-us-west-4.railway.app:$5638/$railway
    username: postgres
    password: rYWJhVuTf4LzyptY68BT
    name: railway

    sql:
      init:
        mode: always