spring:
  datasource:
    url: jdbc:postgresql://postgres:rYWJhVuTf4LzyptY68BT@containers-us-west-4.railway.app:5638/railway
    username: postgres
    password: rYWJhVuTf4LzyptY68BT
    name: Order Service

    sql:
      init:
        mode: always